.TH glances 1  "May, 2015" "version 2.4.2" "USER COMMANDS"
.SH NAME
glances \- A cross-platform curses-based system monitoring tool
.SH SYNOPSIS
.B glances
.RI [ OPTIONS ]
.SH DESCRIPTION
Glances is a free (LGPL) cross-platform curses-based system monitoring tool which
aims to present a maximum of information in a minimum of space, ideally to fit in
a classical 80x24 terminal or higher to have additional information. It can adapt
dynamically the displayed information depending on the terminal size.
.PP
Glances can also work in client/server mode. Remote monitoring could be done via
terminal or web interface.
.PP
This tool is written in Python and uses the psutil library to fetch the statistical
values from key elements, like CPU, load average, memory, network, disks, file
systems, processes and so on.
.SH COMMAND-LINE OPTIONS
The command-line options are the following:
.TP
.B \-h, \-\-help
show this help message and exit
.TP
.B \-V, \-\-version
show program's version number and exit
.TP
.B \-d, \-\-debug
enable debug mode (log file is /tmp/glances.log)
.TP
.B \-C CONF_FILE, \-\-config CONF_FILE
path to the configuration file
.TP
.B \-\-disable-quicklook
disable quick look module
.TP
.B \-\-full-quicklook
disable all but quick look and load modules
.TP
.B \-\-disable-cpu
disable CPU module
.TP
.B \-\-disable-mem
disable MEM module
.TP
.B \-\-disable-swap
disable SWAP module
.TP
.B \-\-disable-load
disable LOAD module
.TP
.B \-\-disable-network
disable network module
.TP
.B \-\-disable-ip
disable IP module
.TP
.B \-\-disable-diskio
disable disk I/O module
.TP
.B \-\-disable-fs
disable file system module
.TP
.B \-\-disable-sensors
disable sensors module
.TP
.B \-\-disable-hddtemp
disable HDDTemp module
.TP
.B \-\-disable-raid
disable RAID module
.TP
.B \-\-disable-docker
disable Docker module
.TP
.B \-\-disable-left-sidebar
disable network, disk I/O, file system and sensors modules
.TP
.B \-\-disable-process
disable process module
.TP
.B \-\-disable-log
disable log module
.TP
.B \-\-disable-bold
disable bold mode in the terminal
.TP
.B \-\-enable-process-extended
enable extended stats on top process
.TP
.B \-\-enable-history
enable the history mode (matplotlib needed)
.TP
.B \-\-path-history PATH_HISTORY
set the export path for graph history
.TP
.B \-\-export-csv EXPORT_CSV
export stats to a CSV file
.TP
.B \-\-export-influxdb
export stats to an InfluxDB server (influxdb needed)
.TP
.B \-\-export-opentsdb
export stats to an OpenTSDB server (potsdb needed)
.TP
.B \-\-export-statsd
export stats to a StatsD server (statsd needed)
.TP
.B \-\-export-rabbitmq
export stats to a RabbitMQ server (pika needed)
.TP
.B \-c CLIENT, \-\-client CLIENT
connect to a Glances server by IPv4/IPv6 address or hostname
.TP
.B \-s, \-\-server
run Glances in server mode
.TP
.B \-\-browser
start the client browser (display list of servers)
.TP
.B \-\-disable-autodiscover
disable autodiscover feature
.TP
.B \-p PORT, \-\-port PORT
define the client/server TCP port [default: 61209]
.TP
.B \-B BIND_ADDRESS, \-\-bind BIND_ADDRESS
bind server to the given IPv4/IPv6 address or hostname
.TP
.B \-\-password
define a client/server password
.TP
.B \-\-snmp-community SNMP_COMMUNITY
SNMP community
.TP
.B \-\-snmp-port SNMP_PORT
SNMP port
.TP
.B \-\-snmp-version SNMP_VERSION
SNMP version (1, 2c or 3)
.TP
.B \-\-snmp-user SNMP_USER
SNMP username (only for SNMPv3)
.TP
.B \-\-snmp-auth SNMP_AUTH
SNMP authentication key (only for SNMPv3)
.TP
.B \-\-snmp-force
force the SNMP mode (do not try Glances server)
.TP
.B \-t TIME, \-\-time TIME
set refresh time in seconds [default: 3 sec]
.TP
.B \-w, \-\-webserver
run Glances in web server mode (bottle needed)
.TP
.B \-q, \-\-quiet
run Glances in quiet mode (nothing is displayed)
.TP
.B \-f PROCESS_FILTER, \-\-process\-filter PROCESS_FILTER
set the process filter pattern (regular expression)
.TP
.B \-\-process-short-name
force short name for processes name
.TP
.B \-\-disable-irix
Task's cpu usage will be divided by the total number of CPUs
.TP
.B \-\-hide-kernel-threads
hide kernel threads in process list
.TP
.B \-\-tree
display processes as a tree
.TP
.B \-b, \-\-byte
display network rate in byte per second [default: bit per second]
.TP
.B \-\-fahrenheit
display temperature in Fahrenheit (default is Celsius)
.TP
.B \-1, \-\-percpu
start Glances in per CPU mode
.TP
.B \-\-fs-free-space
display file system free space instead of used
.TP
.B \-\-theme-white
optimize display colors for white background
.SH INTERACTIVE COMMANDS
You can use the following keys while in Glances:
.TP
.B ENTER
Set the process filter pattern (as a regular expression)
.TP
.B a
Sort process list automatically
.TP
.B b
Switch between bit/s or Byte/s for network I/O
.TP
.B c
Sort processes by CPU usage
.TP
.B d
Show/hide disk I/O stats
.TP
.B e
Enable/disable top extended stats
.TP
.B f
Show/hide file system stats
.TP
.B F
Switch between file system used and free space
.TP
.B g
Generate graphs for current history
.TP
.B h
Show/hide the help screen
.TP
.B i
Sort processes by I/O rate
.TP
.B l
Show/hide log messages
.TP
.B m
Sort processes by MEM usage
.TP
.B n
Show/hide network stats
.TP
.B p
Sort processes by name
.TP
.B q
Quit
.TP
.B r
Reset history
.TP
.B s
Show/hide sensors stats
.TP
.B t
Sort process by CPU times (TIME+)
.TP
.B T
View network I/O as combination
.TP
.B u
Sort processes by USER
.TP
.B U
View cumulative network I/O
.TP
.B w
Delete finished warning log messages
.TP
.B x
Delete finished warning and critical log messages
.TP
.B z
Show/hide processes stats
.TP
.B z
Show/hide processes list (for low CPU consumption)
.TP
.B 0
Task's cpu usage will be divided by the total number of CPUs
.TP
.B 1
Switch between global CPU and per-CPU stats
.TP
.B 2
Enable/disable left sidebar
.TP
.B 3
Enable/disable the quick look module
.TP
.B 4
Enable/disable all but quick look and load module
.TP
.B /
Switch between short name/command line (processes name)
.SH EXAMPLES
.TP
Monitor local machine (standalone mode):
.B $ glances
.PP
Monitor local machine with the Web interface (Web UI):
.B $ glances -w
.PP
Glances web server started on http://0.0.0.0:61208/
.PP
Monitor local machine and export stats to a CSV file (standalone mode):
.B $ glances --export-csv
.PP
Monitor local machine and export stats to a InfluxDB server with 5s refresh time (standalone mode):
.B $ glances -t 5 --export-influxdb
.PP
Monitor local machine and export stats to a RabbitMQ server with 5s refresh time (standalone mode):
.B $ glances -t 5 --export-rabbitmq
.PP
Start a Glances server (server mode):
.B $ glances -s
.PP
Connect Glances to a Glances server (client mode):
.B $ glances -c <ip_server>
.PP
Connect Glances to a Glances server and export stats to a StatsD server (client mode):
.B $ glances -c <ip_server> --export-statsd
.PP
Start the client browser (browser mode):
.B $ glances --browser
.PP
.SH EXIT STATUS
Glances returns a zero exit status if it succeeds to print/grab information.
.PP
It returns 2 if it fails to parse its options (missing arguments, invalid value, etc).
.SH AUTHOR
Glances is written by Nicolas Hennion aka Nicolargo (contact@nicolargo.com)
