version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/glances/outputs/static"
    schedule:
      interval: "weekly"
    groups:
      npm:
        patterns:
          - "*"
