name: glances
version: '3.1.0'
summary: Glances an Eye on your system. A top/htop alternative.
description: |
  Glances is a cross-platform monitoring tool which aims to present
  a maximum of information in a minimum of space through a curses or
  Web based interface. It can adapt dynamically the displayed information
  depending on the user interface size.

grade: stable
confinement: strict

apps:
  glances:
    command: bin/glances
    plugs:
      - network
      - system-observe
      - mount-observe
      - hardware-observe
      - log-observe
      - network-observe
      - physical-memory-observe
      - upower-observe

parts:
  glances:
    build-packages:
    - gcc
    plugin: python
    source: https://github.com/nicolargo/glances.git
  bottle:
    plugin: python
    source: https://github.com/bottlepy/bottle.git
  docker:
    plugin: python
    source: https://github.com/docker/docker-py.git
