name: glances
version: set-by-version-script
version-script: git describe --always --dirty --tags --match 'v*' | sed s/^v//
summary: Glances an Eye on your system. A top/htop alternative.
description: |
  Glances is a cross-platform monitoring tool which aims to present
  a maximum of information in a minimum of space through a curses or
  Web based interface. It can adapt dynamically the displayed information
  depending on the user interface size.

grade: stable
confinement: strict

apps:
  glances:
    command: bin/glances
    plugs:
      - network
      - system-observe
      - mount-observe
      - hardware-observe
      - log-observe
      - network-observe
      - physical-memory-observe
      - upower-observe
      - home
    environment:
      LANG: C.UTF-8
      LC_ALL: C.UTF-8

parts:
  glances:
    plugin: python
    source: .
  bottle:
    plugin: python
    source: https://github.com/bottlepy/bottle.git
  docker:
    plugin: python
    source: https://github.com/docker/docker-py.git
